/* b44-full-sync 2026-06-01 */
export const MOCK_PROFILES = [
  {
    id: 'mock-1',
    name: 'Алина',
    age: 24,
    city: 'Москва',
    is_online: true,
    is_verified: true,
    photos: ['https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=600&fit=crop'],
    bio: 'Люблю кофе, путешествия и хорошие разговоры допоздна',
    interests: ['Путешествия', 'Кино', 'Йога'],
  },
  {
    id: 'mock-2',
    name: 'Катя',
    age: 22,
    city: 'Санкт-Петербург',
    is_online: false,
    is_verified: false,
    photos: ['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=600&fit=crop'],
    bio: 'Художница. Рисую акварелью и мечтаю о Японии',
    interests: ['Арт', 'Музыка', 'Книги'],
  },
  {
    id: 'mock-3',
    name: 'Маша',
    age: 26,
    city: 'Екатеринбург',
    is_online: true,
    is_verified: true,
    photos: ['https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=600&fit=crop'],
    bio: 'Бегаю марафоны и готовлю по воскресеньям. Оптимист по жизни',
    interests: ['Спорт', 'Готовка', 'Природа'],
  },
  {
    id: 'mock-4',
    name: 'Юля',
    age: 23,
    city: 'Казань',
    is_online: false,
    is_verified: false,
    photos: ['https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=600&fit=crop'],
    bio: 'Разработчик днём, геймер ночью. Обожаю инди-игры',
    interests: ['Игры', 'Кино', 'Музыка'],
  },
  {
    id: 'mock-5',
    name: 'Вика',
    age: 25,
    city: 'Новосибирск',
    is_online: true,
    is_verified: true,
    photos: ['https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=600&fit=crop'],
    bio: 'Фотограф. Снимаю природу и людей. Карелия — моя любовь',
    interests: ['Фото', 'Природа', 'Путешествия'],
  },
  {
    id: 'mock-6',
    name: 'Даша',
    age: 21,
    city: 'Краснодар',
    is_online: false,
    is_verified: false,
    photos: ['https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=600&fit=crop'],
    bio: 'Танцую хип-хоп и учусь петь. Музыка — это всё',
    interests: ['Танцы', 'Музыка', 'Арт'],
  },
  {
    id: 'mock-7',
    name: 'Соня',
    age: 27,
    city: 'Москва',
    is_online: true,
    is_verified: true,
    photos: ['https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=600&fit=crop'],
    bio: 'Маркетолог, люблю подкасты и велосипедные прогулки',
    interests: ['Велоспорт', 'Подкасты', 'Кофе'],
  },
];

export const MOCK_CONVERSATIONS = {
  'mock-1': [
    { id: 'm1-1', sender: 'them', type: 'text', content: 'Привет! Ты тоже из Москвы? 👋', time: '18:02' },
    { id: 'm1-2', sender: 'me', type: 'text', content: 'Да, живу тут уже 3 года!', time: '18:04' },
    { id: 'm1-3', sender: 'them', type: 'text', content: 'Классно! Где обычно проводишь время?', time: '18:05' },
    { id: 'm1-4', sender: 'me', type: 'text', content: 'Парк Горького, Нескучный сад — места любимые', time: '18:07' },
    { id: 'm1-5', sender: 'them', type: 'text', content: 'Ооо, я там бегаю по утрам! Может встретимся как-нибудь? 😊', time: '18:10' },
  ],
  'mock-2': [
    { id: 'm2-1', sender: 'them', type: 'text', content: 'Привет! Видела твой профиль — ты тоже любишь кино?', time: '15:30' },
    { id: 'm2-2', sender: 'me', type: 'text', content: 'Да, особенно люблю европейский арт-хаус 🎬', time: '15:32' },
    { id: 'm2-3', sender: 'them', type: 'text', content: 'Серьёзно?! Я недавно пересматривала Тати', time: '15:33' },
    { id: 'm2-4', sender: 'me', type: 'text', content: '"Каникулы господина Юло" — шедевр абсолютный', time: '15:45' },
    { id: 'm2-5', sender: 'them', type: 'text', content: 'Точно! Слушай, хочешь созвониться на 3 минуты?', time: '16:00' },
    { id: 'm2-6', sender: 'me', type: 'text', content: 'Кстати, покажешь свои работы?', time: '16:10' },
    { id: 'm2-7', sender: 'them', type: 'system', content: '📹 Катя предложила видео-встречу на 3 минуты', time: '16:12' },
  ],
  'mock-3': [
    { id: 'm3-1', sender: 'me', type: 'text', content: 'Привет! Ты правда бегаешь марафоны?', time: '09:15' },
    { id: 'm3-2', sender: 'them', type: 'text', content: 'Привет! Да, уже 3 года. В мае пробежала Московский 💪', time: '09:20' },
    { id: 'm3-3', sender: 'me', type: 'text', content: 'Это нереально круто! Как ты к этому пришла?', time: '09:21' },
    { id: 'm3-4', sender: 'them', type: 'text', content: 'Начинала с 5 км, потом затянуло. Хочешь попробовать?', time: '09:25' },
    { id: 'm3-5', sender: 'me', type: 'text', content: 'Давай попробуем! Только не сразу марафон 😅🏃', time: '09:30' },
  ],
  'mock-4': [
    { id: 'm4-1', sender: 'them', type: 'text', content: 'Привет! Видела в профиле — тоже в игры?', time: '22:00' },
    { id: 'm4-2', sender: 'me', type: 'text', content: 'Привет! Да, но в основном инди-игры', time: '22:05' },
    { id: 'm4-3', sender: 'them', type: 'text', content: 'О, какие? Я сейчас прохожу Hades второй раз 😅', time: '22:07' },
    { id: 'm4-4', sender: 'me', type: 'text', content: 'Hades — огонь! Саундтрек там просто нереальный 🔥', time: '22:10' },
  ],
  'mock-5': [
    { id: 'm5-1', sender: 'them', type: 'text', content: 'Привет! Видела твои снимки — очень крутые ракурсы', time: '11:00' },
    { id: 'm5-2', sender: 'me', type: 'text', content: 'Спасибо! Ты тоже снимаешь?', time: '11:05' },
    { id: 'm5-3', sender: 'them', type: 'text', content: 'Пейзажи в основном, природа 🌿 Недавно была в Карелии', time: '11:06' },
    { id: 'm5-4', sender: 'me', type: 'text', content: 'Надо как-нибудь вместе съездить на съёмку!', time: '11:15' },
    { id: 'm5-5', sender: 'them', type: 'text', content: 'Давай! Ты в каких местах снимаешь обычно?', time: '11:20' },
    { id: 'm5-6', sender: 'me', type: 'text', content: 'Подмосковье, Звенигород, иногда еду в Карелию', time: '11:22' },
  ],
  'mock-6': [
    { id: 'm6-1', sender: 'them', type: 'text', content: 'Привет! Ты танцуешь?', time: '20:00' },
    { id: 'm6-2', sender: 'me', type: 'text', content: 'Немного! Больше слушаю и кайфую от музыки 🎵', time: '20:05' },
    { id: 'm6-3', sender: 'them', type: 'text', content: 'А что слушаешь?', time: '20:07' },
  ],
  'mock-7': [
    { id: 'm7-1', sender: 'them', type: 'text', content: 'Привет! Я Соня, видела что ты тоже из Москвы 🙂', time: '14:00' },
    { id: 'm7-2', sender: 'me', type: 'text', content: 'Привет Соня! Да, живу тут давно', time: '14:05' },
    { id: 'm7-3', sender: 'them', type: 'text', content: 'Катаешься на велосипеде? Я недавно новый маршрут нашла вдоль Яузы', time: '14:08' },
  ],
};

export const MOCK_CHAT_LIST = [
  { id: 'mock-1', profileId: 'mock-1', lastMessage: 'Может встретимся как-нибудь? 😊', time: '18:10', unread: 1 },
  { id: 'mock-7', profileId: 'mock-7', lastMessage: 'Новый маршрут вдоль Яузы 🚴', time: '14:08', unread: 2 },
  { id: 'mock-2', profileId: 'mock-2', lastMessage: '📹 Катя предложила видео-встречу', time: '16:12', unread: 1 },
  { id: 'mock-3', profileId: 'mock-3', lastMessage: 'Только не сразу марафон 😅', time: '09:30', unread: 0 },
  { id: 'mock-5', profileId: 'mock-5', lastMessage: 'Подмосковье, Звенигород...', time: '11:22', unread: 3 },
  { id: 'mock-4', profileId: 'mock-4', lastMessage: 'Саундтрек там нереальный 🔥', time: 'вчера', unread: 0 },
  { id: 'mock-6', profileId: 'mock-6', lastMessage: 'А что слушаешь?', time: 'вчера', unread: 0 },
];